### ISSUE TITLE
Optimizing `rebuild` for the label-trigger scenario?

### ISSUE THREAD

**Issue by icecrime** [icecrime/poule#8]
The `rebuild` operation currently supports a single trigger label. If you want to configure multiple label to configuration associations, you need to repeat yourself in the configuration:

```yaml
    - repositories:     [ "docker/docker" ]
      triggers:
          pull_request: [ labeled ]
      operations:
          - type:       rebuild
            settings: {
                configurations: [ arm ],
                label:          "rebuild/arm",
            }
          - type:       rebuild
            settings: {
                configurations: [ experimental ],
                label:          "rebuild/experimental",
            }
```

Question: is that a good approach, or should `rebuild` made aware of a label to configuration mapping?
